Repository jetstack/cert-manager-nginx-plus-lab, pull requests merged in 2020-03, with the labels that each got.

#15 Add extra info on the components running
  README.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#17 Add a service to the diagram
  images/diagram-ingress.png
Labels: approved, dco-signoff: yes, lgtm, size/XS

#21 updated readme
  .DS_Store
  README.md
  images/NGINX Plus.svg
  images/NGINX-Ingress-Controller-4-services-1024x547.png
  images/NGINXPlus-K8s.svg
  images/NGINXPlus-K8sWorkload.svg
Labels: approved, dco-signoff: yes, lgtm, size/L

#16 Issue a certificate move workload to top
  README.md
  certificate.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#22 Add a ping-pong example
  README.md
  images/pingpong.png
  pingpong.yaml
  pingpong/Dockerfile
  pingpong/main.go
  setup-pingpong-image.sh
Labels: approved, dco-signoff: yes, lgtm, size/L

#23 Remove duration from the lab
  README.md
  certificate.yaml
  workload.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#24 Install cert-manager 0.14.1
  README.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#31 Fix typo in demo certificate
  certificate.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#34 Fix the zone
  README.md
  venafi-issuer.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#33 Improved pingpong
  README.md
  pingpong.yaml
  pingpong/main.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#25 Add mistakes to troubleshoot
  README.md
  mistakes/mistake-1.yaml
  mistakes/mistake-2.yaml
  mistakes/mistake-3.yaml
  mistakes/mistake-4.yaml
  mistakes/mistake-5.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#39 Setup bash completion
  setup-k8s.sh
Labels: approved, dco-signoff: yes, lgtm, size/XS

#38 Fix executable permissions
  reset.sh
Labels: approved, dco-signoff: yes, lgtm, size/XS

#43 Add back lost docs on cert-manager components
  README.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#42 Add note on TPP url for pingpong
  README.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#45 Add an example with x509 subject
  README.md
  certificate-subject.yaml
  images/subject.png
Labels: approved, dco-signoff: yes, lgtm, size/M

#48 Whitespace cleanup
  README.md
Labels: approved, dco-signoff: yes, lgtm, size/M
